const roles = {
  ADMIN: "ADMIN",
  EDITOR: "EDITOR",
  GUEST: "GUEST",
};

const actions = {
  ADD_PRODUCT: "ADD_PRODUCT",
  MODIFY_PRODUCT: "MODIFY_PRODUCT",
  REMOVE_PRODUCT: "REMOVE_PRODUCT",
  VIEW_PRODUCT: "VIEW_PRODUCT",
  REMOVE_SELL: "REMOVE_SELL",
  VIEW_SELL: "VIEW_INFORMATION",
};
